Repository pywbem/pywbem, pull requests merged in 2018-04, with the labels that each got.

#1165 Updated help text of mof_compiler script
  docs/mof_compiler.help.txt
Labels: priority

#1197 Start 0.12.1
  docs/changes.rst
Labels: priority

#1200 Start 0.13.0
  docs/changes.rst
Labels: priority

#1203 Release 0.12.1
  README.rst
  docs/changes.rst
Labels: priority

#1204 Added a README file for Pypi
  DEVELOP.md
  README_PYPI.rst
  setup.cfg
Labels: priority

#1211 Start 0.12.2
  docs/changes.rst
Labels: priority

#1212 Add pywbem.py to depends file list for recreating docs/wbemcli_help_txt file
  docs/changes.rst
  docs/wbemcli.help.txt
  makefile
Labels: priority

#1216 Fixes #848: Moved class NocaseDict into its own submodule _nocasedict.py
  docs/changes.rst
  docs/client/objects.rst
  makefile
  pywbem/__init__.py
  pywbem/_nocasedict.py
  pywbem/_recorder.py
  pywbem/_server.py
  pywbem/_utils.py
  pywbem/cim_http.py
  pywbem/cim_obj.py
  pywbem/cim_operations.py
  pywbem/cim_types.py
  pywbem/mof_compiler.py
  pywbem/tupleparse.py
  pywbem_mock/_wbemconnection_mock.py
  testsuite/test_cim_obj.py
  testsuite/test_cim_xml.py
  testsuite/test_client.py
  testsuite/test_mof_compiler.py
  testsuite/test_nocasedict.py
  testsuite/test_wbemconnection_mock.py
  testsuite/test_wbemserverclass.py
  testsuite/unittest_extensions.py
  testsuite/validate.py
Labels: review needed

#1217 fixes #1160 Enhance MOF compiler and missing dependent classes resolution logic
  docs/changes.rst
  pywbem/mof_compiler.py
  testsuite/test_mof_compiler.py
  testsuite/testmofs/test_refs.mof
Labels: review needed

#1229 Fixes #1228 Fixes Error in mof_compiler CIMError Description text
  pywbem/mof_compiler.py
  testsuite/test_mof_compiler.py
Labels: priority

#1234 Fixed description of test_conftest.py module.
  testsuite/testclient/test_conftest.py
Labels: priority

#1220 Fixes #1187 #1218 Add capability to pywbem_mock to get DMTF schema
  .gitignore
  docs/mocksupport.rst
  makefile
  pywbem/mof_compiler.py
  pywbem_mock/__init__.py
  pywbem_mock/_dmtf_cim_schema.py
  pywbem_mock/_wbemconnection_mock.py
  testsuite/dmtf_mof_schema_def.py
  testsuite/run_cim_operations.py
  testsuite/test_logging.py
  testsuite/test_mof_compiler.py
  testsuite/test_recorder.py
  testsuite/test_wbemconnection_mock.py
  testsuite/test_wbemserverclass.py
Labels: review needed

#1230 Fixes #1221 mof_compiler change use of args[0] etc.
  docs/changes.rst
  pywbem/mof_compiler.py
  testsuite/test_mof_compiler.py
Labels: review needed

#1239 Issue #1201 Small improvements in test_function decorator and its test functions
  testsuite/pytest_extensions.py
  testsuite/test_cim_obj.py
  testsuite/test_cim_types.py
  testsuite/test_nocasedict.py
  testsuite/test_tupleparse.py
Labels: priority, review needed
