Repository pywbem/pywbem, pull requests merged in 2018-09, with the labels that each got.

#1362 Updated PKG-INFO
  PKG-INFO
Labels: priority

#1370 Fixes #1371: Pinned version of pytest-cov to <2.6
  dev-requirements.txt
Labels: priority, rollback needed

#1372 Start 0.12.6
  docs/changes.rst
Labels: priority

#1375 Change log for pinning pytest-cov version to <2.6
  docs/changes.rst
Labels: rollback done

#1368 Fixes #1355: Issues with case insensitivity on classnames in pywbem_mock
  PKG-INFO
  docs/changes.rst
  pywbem_mock/_wbemconnection_mock.py
  testsuite/test_wbemconnection_mock.py
Labels: rollback needed

#1381 Fixes #1379: Added support for asterisks to CIMDateTime
  docs/changes.rst
  pywbem/cim_types.py
  testsuite/test_cim_types.py
  testsuite/test_recorder.py
Labels: priority, rollback needed

#1383 Fixes #1380: Fixed issue of missing support for INSTANCE child elements of ERROR
  docs/changes.rst
  pywbem/cim_operations.py
  pywbem/exceptions.py
  pywbem/tupleparse.py
  testsuite/test_exceptions.py
  testsuite/testclient/conftest.py
  testsuite/testclient/getinstance.yaml
Labels: priority, rollback needed

#1391 Fixes issue #1227. mof compiler search path extended to allow string
  docs/changes.rst
  pywbem/mof_compiler.py
  testsuite/test_mof_compiler.py
Labels: review needed

#1403 [Review 3] Improved _uprint() by supporting byte strings
  pywbem_mock/_wbemconnection_mock.py
  testsuite/run_uprint.py
  testsuite/test_utils.py
Labels: discussion needed
