Repository pywbem/pywbem, pull requests merged in 2018-06, with the labels that each got.

#1267 Refactor test_wbemserverclass.py
  testsuite/instance_from_class_method.py
  testsuite/test_wbemconnection_mock.py
  testsuite/test_wbemserverclass.py
  testsuite/wbemserver_mock.py
Labels: release: mandatory, type: cleanup

#1277 fixes #1276 mock repository_display() unicode issue
  PKG-INFO
  docs/changes.rst
  pywbem_mock/_wbemconnection_mock.py
  testsuite/test_uprint.bat
  testsuite/test_wbemconnection_mock.py
Labels: review needed

#1248 Increased M2Crypto to 0.30.1; Used M2Crypto on Windows
  README.rst
  appveyor.yml
  docs/appendix.rst
  docs/changes.rst
  docs/intro.rst
  docs/wbemcli.help.txt
  makefile
  minimum-constraints.txt
  pywbem_os_setup.bat
  pywbem_os_setup.sh
  requirements.txt
  rtd-requirements.txt
  win32-requirements.txt
  win64-requirements.txt
Labels: priority, review needed

#1286 Removed prints from test runs
  testsuite/run_uprint.py
  testsuite/test_recorder.py
  testsuite/test_subscriptionmanager.py
  testsuite/test_wbemconnection_mock.py
  testsuite/test_wbemserverclass.py
Labels: area: test, type: cleanup

#1294 Fixed determination of package version for Linux.
  .travis.yml
  makefile
Labels: priority

#1297 Resolved some more pylint findings
  pywbem/_valuemapping.py
  testsuite/run_uprint.py
  testsuite/simple_mock_add_obj.py
  testsuite/test_valuemapping.py
  testsuite/test_wbemserverclass.py
  testsuite/testclient/conftest.py
  testsuite/testclient/test_conftest.py
Labels: review needed

#1301 Fixes #1298 null value keybindings
  PKG-INFO
  docs/changes.rst
  docs/wbemcli.help.txt
  pywbem/cim_obj.py
  pywbem/config.py
  testsuite/test_cim_obj.py
Labels: review needed
