Repository pywbem/pywbem, pull requests merged in 2018-05, with the labels that each got.

#1249 Convert test_logging to use only pytest
  testsuite/test_logging.py
Labels: review needed

#1257 Start 0.12.3
  docs/changes.rst
Labels: priority

#1260 fixes #1256 Correct issue in pywbem_mock with incorrect CIMError return
  docs/changes.rst
  pywbem_mock/_wbemconnection_mock.py
Labels: priority, release: mandatory, type: bug

#1254 Fixes #1253 Fix issue with deepcopy of objects in _wbemconnection_mock
  docs/changes.rst
  pywbem_mock/_wbemconnection_mock.py
  testsuite/test_wbemconnection_mock.py
Labels: priority, release: mandatory, type: bug

#1269 Fixes #1268 Add input parameter to wbemcli to allow mocking a server
  docs/changes.rst
  pywbem_mock/_wbemconnection_mock.py
  testsuite/simple_mock_add_obj.py
  testsuite/simple_mock_model.mof
  testsuite/test_wbemcli.py
  wbemcli.py
Labels: review needed, type: enhancement
