Repository pywbem/pywbem, pull requests merged in 2019-02, with the labels that each got.

#1634 Fixed F811 and E117 issues reported by new flake8 3.7
  .flake8
  pywbem/_recorder.py
  tests/end2endtest/test_profile_generic.py
  tests/end2endtest/test_profile_snia_server.py
  tests/end2endtest/test_profile_snia_smis.py
  tests/end2endtest/test_server.py
Labels: priority

#1406 Fixes #1398: Clarified how to determine scoping class/path if not specified in profile
  docs/appendix.rst
  docs/changes.rst
  pywbem/_server.py
Labels: update needed

#1637 Add method to reset statistics
  docs/changes.rst
  pywbem/_statistics.py
  tests/unittest/pywbem/test_statistics.py
Labels: review needed

#1638 Extend the manual test run_enum_performance.py to gather info
  tests/manualtest/run_enum_performance.py
Labels: update needed

#1543 [WIP] Fixes #1540: Extend WBEMConnection_mock class resolution
  PKG-INFO
  docs/changes.rst
  docs/mocksupport.rst
  pywbem_mock/__init__.py
  pywbem_mock/_mockmofwbemconnection.py
  pywbem_mock/_resolvermixin.py
  pywbem_mock/_wbemconnection_mock.py
  tests/unittest/pywbem/test_recorder.py
  tests/unittest/pywbem/test_wbemserverclass.py
  tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Labels: review needed

#1657 Extend makefile to remove cover files from pywbem_mock
  docs/changes.rst
  makefile
Labels: review needed
