Repository pywbem/pywbem, pull requests merged in 2019-11, with the labels that each got.

#1929 Improved coverage of function tests via last_* connection attrs
  docs/changes.rst
  pywbem/cim_operations.py
  tests/functiontest/README.md
  tests/functiontest/associatornames_classes.yaml
  tests/functiontest/associatornames_instances.yaml
  tests/functiontest/associators_classes.yaml
  tests/functiontest/associators_instances.yaml
  tests/functiontest/clienterror.yaml
  tests/functiontest/closeenumeration.yaml
  tests/functiontest/conftest.py
  tests/functiontest/createclass.yaml
  tests/functiontest/createinstance.yaml
  tests/functiontest/deleteclass.yaml
  tests/functiontest/deleteinstance.yaml
  tests/functiontest/deletequalifier.yaml
  tests/functiontest/embeddedinstances.yaml
  tests/functiontest/embeddedobjectclasses.yaml
  tests/functiontest/embeddedobjectinstances.yaml
  tests/functiontest/enumerateclasses.yaml
  tests/functiontest/enumerateclassnames.yaml
  tests/functiontest/enumerateinstancenames.yaml
  tests/functiontest/enumerateinstances.yaml
  tests/functiontest/enumeratequalifiers.yaml
  tests/functiontest/execquery.yaml
  tests/functiontest/getalltypes.yaml
  tests/functiontest/getclass.yaml
  tests/functiontest/getinstance.yaml
  tests/functiontest/getqualifier.yaml
  tests/functiontest/invalidresponseerror.yaml
  tests/functiontest/invokemethod.yaml
  tests/functiontest/modifyclass.yaml
  tests/functiontest/modifyinstance.yaml
  tests/functiontest/openassociatorinstances.yaml
  tests/functiontest/openasssociatorinstancepaths.yaml
  tests/functiontest/openenumerateinstancepaths.yaml
  tests/functiontest/openenumerateinstances.yaml
  tests/functiontest/openqueryinstances.yaml
  tests/functiontest/openreferenceinstancepaths.yaml
  tests/functiontest/openreferenceinstances.yaml
  tests/functiontest/pullinstancepaths.yaml
  tests/functiontest/pullinstances.yaml
  tests/functiontest/pullinstanceswithpath.yaml
  tests/functiontest/referencenames_classes.yaml
  tests/functiontest/referencenames_instances.yaml
  tests/functiontest/references_classes.yaml
  tests/functiontest/references_instances.yaml
  tests/functiontest/setqualifier.yaml
Labels: area: test, type: enhancement

#1943 Ks/#add log to mof compiler options
  docs/changes.rst
  mof_compiler
Labels: roll back needed

#1953 0.15: Add --log to mof_compiler options (#1943)
  docs/changes.rst
  mof_compiler
Labels: area: code, type: enhancement

#1960 Fixes #1941: documentation full TOC
  dev-requirements.txt
  docs/conf.py
  docs/index.rst
  docs/mof_compiler.help.txt
  minimum-constraints.txt
  rtd-requirements.txt
Labels: roll back/forward done

#1961 Fixes #1933: Fixed that local tests skipped MOF tests if mof*tab files did not exist
  docs/changes.rst
  tests/utils.py
Labels: roll back/forward done

#1962 Fixes #1958: Mocker adds path to new instance on CreateInstance
  docs/changes.rst
  pywbem_mock/_mockmofwbemconnection.py
  tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Labels: roll back/forward done

#1949 Fixes #1945: Fixed python2.7 command not found in CygWin in Appveyor
  appveyor.yml
  docs/changes.rst
Labels: review needed

#1957 Fixes #1956: mof_compiler does not send CreateInstance, CreateClass to conn
  docs/changes.rst
  mof_compiler
  pywbem/mof_compiler.py
  tests/unittest/pywbem/test.mof
  tests/unittest/pywbem/test_mof_compiler.py
Labels: roll back needed, update needed
