Repository pywbem/pywbem, pull requests merged in 2019-01, with the labels that each got.

#1565 Fixes #1564: Added toleration support for CIM-XML responses with empty TYPE attr
  docs/changes.rst
  pywbem/tupleparse.py
Labels: review needed, test needed

#1569 Fixes #1568: Setting last_raw_request/response independent of debug
  docs/changes.rst
  pywbem/cim_operations.py
Labels: review needed, test needed

#1601 Fixes #1600: Fixed strange failure pattern in Travis
  .travis.yml
Labels: priority

#1596 Fixes #1594: End2end: Support for groups in groups in server definition file
  testsuite/end2end/pytest_end2end.py
  testsuite/end2end/server_file.py
  testsuite/end2end/server_file_example.yml
Labels: update needed

#1615 Fixes #1614 - Fix order of method_callback parameters
  docs/changes.rst
  docs/mocksupport.rst
  pywbem_mock/_wbemconnection_mock.py
Labels: type: bug

#1613 Add notebooks to demo mock capabilities
  docs/changes.rst
  docs/mocksupport.rst
  docs/notebooks/datamodel.ipynb
  docs/notebooks/pywbemmock_part1.ipynb
  docs/notebooks/pywbemmock_part2.ipynb
Labels: discussion needed
