Repository pywbem/pywbem, pull requests merged in 2019-03, with the labels that each got.

#1683 Start 0.13.1
  appveyor.yml
  docs/changes.rst
  makefile
  pywbem_os_setup.bat
Labels: priority

#1686 Master: Fixed pip version issue on Appveyor
  appveyor.yml
  docs/changes.rst
  makefile
  pywbem_os_setup.bat
Labels: priority

#1693 Added retries to curl in pywbem_os_setup.bat
  pywbem_os_setup.bat
Labels: review needed

#1694 Improved Python version checking by using 'python_requires' keyword
  docs/changes.rst
  pywbem/__init__.py
  setup.cfg
  setup.py
Labels: discussion needed

#1699 Modify mof_compiler.py to remove unused production defs.
  docs/changes.rst
  pywbem/mof_compiler.py
Labels: review needed

#1701 Fix issue #1222 Displays log output during tests
  tests/unittest/pywbem/test_recorder.py
Labels: release: optional
