Repository pywbem/pywbem, pull requests merged in 2019-04, with the labels that each got.

#1702 Revamp the pywbemmock notebooks into single file
  docs/changes.rst
  docs/notebooks/DemoMock.ipynb
  docs/notebooks/pywbemmock.ipynb
  docs/notebooks/pywbemmock_part1.ipynb
  docs/notebooks/pywbemmock_part2.ipynb
Labels: review needed

#1742 fixes issue #1741 Jupyter Note book example broken
  docs/changes.rst
  docs/notebooks/iterablecimoperations.ipynb
Labels: review needed, roll back

#1739 Fixes #1736: Improved quality of TypeError exceptions raised for WBEMConnection ops args
  docs/changes.rst
  pywbem/cim_operations.py
Labels: roll back
