Repository pywbem/pywbem, pull requests merged in 2019-09, with the labels that each got.

#1822 Fixes #1820: Fixed handling of ANY scope in mock; improved exceptions
  docs/changes.rst
  pywbem_mock/_resolvermixin.py
Labels: review needed

#1821 0.14: Fixed handling of ANY scope in mock; improved exceptions
  docs/changes.rst
  pywbem_mock/_resolvermixin.py
Labels: waiting

#1828 Fixes #1826: Format of wbemcli option
  tests/unittest/test_wbemcli.py
  wbemcli.py
Labels: roll back needed

#1835 0.14: Skip tests if moftab files do not exist
  tests/utils.py
Labels: roll back/forward done

#1833 0.14: Fix tests to support flexible wbemcli naming
  PKG-INFO
  tests/unittest/test_wbemcli.py
Labels: roll back/forward done

#1847 Fixes #1844: 0.14: Fixed the issue with 'dnf makecache fast' during pywbem_os_setup.sh on Fedora
  docs/changes.rst
  pywbem_os_setup.sh
Labels: roll back/forward done

#1857 Travis: Fixed coveralls to run again for py34/latest
  .travis.yml
Labels: roll back/forward done
