Repository pywbem/pywbem, pull requests merged in 2019-05, with the labels that each got.

#1747 Fix issue in mocker with property list on EnumerateInstance
  docs/changes.rst
  pywbem_mock/_wbemconnection_mock.py
  tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Labels: roll back

#1756 0.14: Upgraded Win32/Win64 OpenSSL from 1.1.0j to 1.1.0k
  docs/appendix.rst
  docs/changes.rst
  pywbem_os_setup.bat
Labels: priority

#1755 Fixes #1754: Upgraded Win32/Win64 OpenSSL from 1.1.0j to 1.1.0k
  docs/appendix.rst
  docs/changes.rst
  pywbem_os_setup.bat
Labels: priority, roll back/forward done

#1758 0.14: Upgraded minimum versions of dependent packages: requests, urllib3, bleach
  dev-requirements.txt
  docs/changes.rst
  minimum-constraints.txt
Labels: priority

#1761 Fix issue in run_response_performance.py
  tests/manualtest/run_response_performance.py
Labels: area: devlopment env, release: mandatory

#1759 Release 0.14.3
  PKG-INFO
  README.rst
  docs/changes.rst
Labels: priority
