Repository pywbem/pywbem, pull requests merged in 2020-03, with the labels that each got.

#2080 Part 2 of pywbem_mock refactor. This pr separates repository from _wbemconnection
  docs/mocksupport.rst
  minimum-constraints.txt
  pywbem_mock/__init__.py
  pywbem_mock/_baserepository.py
  pywbem_mock/_inmemoryrepository.py
  pywbem_mock/_mockmofwbemconnection.py
  pywbem_mock/_resolvermixin.py
  pywbem_mock/_utils.py
  pywbem_mock/_wbemconnection_mock.py
  requirements.txt
  tests/unittest/pywbem/test_mof_compiler.py
  tests/unittest/pywbem/test_wbemserverclass.py
  tests/unittest/pywbem_mock/test_inmemory_repository.py
  tests/unittest/pywbem_mock/test_wbemconnection_mock.py
  tests/unittest/utils/wbemserver_mock.py
Labels: review needed

#2127 Updated minimum package versions for py34/py38
  dev-requirements.txt
  minimum-constraints.txt
  rtd-requirements.txt
Labels: roll back/forward done

#2132 Separate CIM repository from Fake_WBEMConnection
  docs/changes.rst
  pywbem_mock/__init__.py
  pywbem_mock/_cimrepository.py
  pywbem_mock/_mockmofwbemconnection.py
  pywbem_mock/_resolvermixin.py
  pywbem_mock/_wbemconnection_mock.py
  tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Labels: review needed

#2134 Minor cleanup in makefile: tabs/blanks & SHELL
  makefile
Labels: waiting
