Repository pywbem/pywbem, pull requests merged in 2020-04, with the labels that each got.

#2137 Fixes #2135: Fixed installation of Jupyter Notebook on Python 3.4
  dev-requirements.txt
  docs/changes.rst
  minimum-constraints.txt
Labels: roll back/forward done

#2141 Fixes #2139: Pinned dparse to <0.5.0 on Python 2.7 due to an issue
  dev-requirements.txt
  docs/changes.rst
Labels: roll back/forward done

#2161 Fixes #2160: Fixed missing MinutesFromUTC.tzname(); added tests
  dev-requirements.txt
  docs/changes.rst
  minimum-constraints.txt
  pywbem/_cim_types.py
  tests/unittest/pywbem/test_cim_types.py
Labels: roll back/forward done

#2169 Fixes #2167: Increased min version of setuptools on py37
  docs/changes.rst
  minimum-constraints.txt
Labels: roll back/forward done

#2170 0.17: Enabled manual CI run for stable branch; other cleanup in CI files
  .travis.yml
  DEVELOP.md
  appveyor.yml
Labels: roll back/forward done

#2164 Release 0.17.1
  docs/changes.rst
  pywbem/_version.py
Labels: review needed

#2176 0.17: Fixed a virtualenv creation failure during install test
  dev-requirements.txt
  docs/changes.rst
  makefile
  minimum-constraints.txt
  tests/installtest/test_install.sh
Labels: under work

#2175 Fixes #2174: Fixed a virtualenv creation failure during install test
  dev-requirements.txt
  docs/changes.rst
  makefile
  minimum-constraints.txt
  tests/installtest/test_install.sh
Labels: roll back/forward done

#2189 Fixes #2187: Fixed raise error for invalid reference_direction in WBEMServer.get_central_instances()
  docs/changes.rst
  pywbem/_server.py
  tests/unittest/pywbem/test_wbemserverclass.py
Labels: roll back/forward done

#2191 Fixes #2188: Fixed raise error for missing ports in WBEMListener.__init__()
  docs/changes.rst
  pywbem/_listener.py
Labels: roll back/forward done

#2186 [WIP] Issue #2062: Create the DefaultInstanceProvider Class
  pywbem_mock/__init__.py
  pywbem_mock/_baseprovider.py
  pywbem_mock/_defaultinstanceprovider.py
  pywbem_mock/_mainprovider.py
  pywbem_mock/_resolvermixin.py
  pywbem_mock/_wbemconnection_mock.py
  tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Labels: review needed

#2203 Modify mock code to change method name exists to object_exists
  pywbem_mock/_baseprovider.py
  pywbem_mock/_baserepository.py
  pywbem_mock/_defaultinstanceprovider.py
  pywbem_mock/_inmemoryrepository.py
  pywbem_mock/_mainprovider.py
  pywbem_mock/_mockmofwbemconnection.py
  pywbem_mock/_resolvermixin.py
  tests/unittest/pywbem_mock/test_inmemory_repository.py
  tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Labels: review needed

#2202 Issue #2062 part 3c - Create method provider
  docs/mocksupport.rst
  pywbem_mock/_baseprovider.py
  pywbem_mock/_defaultinstanceprovider.py
  pywbem_mock/_wbemconnection_mock.py
  tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Labels: review needed
