Repository pywbem/pywbem, pull requests merged in 2020-10, with the labels that each got.

#2459 Upgraded WinOpenSSL to 1.1.1h
  docs/changes.rst
  pywbem_os_setup.bat
Labels: roll back/forward done

#2462 0.17: Upgraded WinOpenSSL to 1.1.1h
  docs/changes.rst
  pywbem_os_setup.bat
Labels: waiting

#2467 Added pip environment info; Mitigated virtualenv creation issue
  appveyor.yml
  makefile
Labels: roll back/forward done

#2474 Fixes #2449: Test that catches ModifyInstance key property change
  docs/changes.rst
  tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Labels: review needed

#2479 Fixes #464: Finished incomplete embedded instance test
  docs/changes.rst
  tests/unittest/pywbem/test_mof_compiler.py
  tests/unittest/pywbem/testmofs/test_instance.mof
Labels: review needed

#2483 Release 1.1.0
  .travis.yml
  README_PYPI.rst
  appveyor.yml
  docs/changes.rst
  pywbem/_version.py
Labels: waiting

#2504 1.1: Fixes issue #2502 pywbem compiler issue building in second namespace
  pywbem/_mof_compiler.py
  tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Labels: priority

#2515 New MissingKeybindingsWarning warning for instance paths without keys
  docs/changes.rst
  pywbem/_cim_obj.py
  pywbem/_cim_types.py
  pywbem/_tupleparse.py
  pywbem/_warnings.py
  tests/unittest/pywbem/test_cim_http.py
  tests/unittest/pywbem/test_cim_obj.py
  tests/unittest/pywbem/test_tupleparse.py
Labels: roll back/forward done
