Repository pywbem/pywbem, pull requests merged in 2021-05, with the labels that each got.

#2690 Fixed safety issue 40291
  Makefile
  minimum-constraints.txt
Labels: priority, roll back/forward done

#2693 Fix mof_compiler unwanted output of trace log information.
  docs/changes.rst
  pywbem/_mof_compiler.py
Labels: roll back/forward done

#2695 Improved the running of indication listeners when using HTTPS
  docs/changes.rst
  docs/indication.rst
  examples/listen.py
  pywbem/_exceptions.py
  pywbem/_listener.py
  tests/unittest/pywbem/test_exceptions.py
  tests/unittest/pywbem/test_indicationlistener.py
Labels: priority, review needed
