Repository pywbem/pywbem, pull requests merged in 2021-06, with the labels that each got.

#2706 Circumvented safety issues 40380..40386 with the notebook package
  Makefile
  docs/changes.rst
Labels: priority, roll back/forward done

#2710 Allow initalization defined url for FakedWBEMConnection class
  docs/changes.rst
  pywbem_mock/_wbemconnection_mock.py
  tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Labels: review needed

#2702 Fixes issue #2701, SubscriptionManager code issues
  docs/changes.rst
  pywbem/_subscription_manager.py
  tests/unittest/pywbem/test_subscriptionmanager.py
Labels: update needed

#2717 Windows: Removed dependency on bash command in pip upgrade in Makefile
  Makefile
  docs/changes.rst
Labels: roll back/forward done
