Repository pywbem/pywbem, pull requests merged in 2021-07, with the labels that each got.

#2721 Ks/#2704 subscription providers
  docs/changes.rst
  pywbem/_subscription_manager.py
  pywbem_mock/__init__.py
  pywbem_mock/_subscriptionproviders.py
  pywbem_mock/_wbemconnection_mock.py
  tests/unittest/pywbem/test_subscriptionmanager.py
  tests/unittest/utils/wbemserver_mock.py
Labels: review needed

#2723 Ks/#2712 add subscription properties
  docs/changes.rst
  pywbem/_subscription_manager.py
  pywbem_mock/_subscriptionproviders.py
  tests/unittest/pywbem/test_subscriptionmanager.py
Labels: review needed

#2724 Ks/#2722 modify subscript provider
  docs/changes.rst
  pywbem_mock/_subscriptionproviders.py
  tests/unittest/pywbem/test_subscriptionmanager.py
Labels: review needed

#2733 Fixed errors in header values in WBEM listener
  docs/changes.rst
  pywbem/_listener.py
  tests/unittest/pywbem/test_indicationlistener.py
Labels: roll back/forward done

#2738 Tolerated servers returning CIM_ERR_FAILED when not supporting pull ops
  docs/changes.rst
  pywbem/_cim_operations.py
Labels: roll back/forward done

#2746 Fixed yamlloader error during setup.py install on Ubuntu with py27/34/35
  docs/changes.rst
  minimum-constraints.txt
  requirements.txt
Labels: priority, roll back/forward done

#2744 Issue #2742 - Add tests for instance create of abstract class
  docs/changes.rst
  pywbem/_mof_compiler.py
  pywbem_mock/_instancewriteprovider.py
  pywbem_mock/_providerdispatcher.py
  tests/unittest/pywbem_mock/test_wbemconnection_mock.py
Labels: update needed
