Repository pywbem/pywbem, pull requests merged in 2023-01, with the labels that each got.

#2972 Fixed missing astroid requirement on typing-extensions
  dev-requirements.txt
  minimum-constraints.txt
Labels: waiting

#2968 Use a new docker image in tests.
  docs/changes.rst
  tests/end2endtest/es_server.yml
Labels: area: test

#2969 Fix issue with HTTP retries of cim-xml operations.
  docs/changes.rst
  pywbem/_cim_operations.py
Labels: review needed

#2975 Disable CI test failure upon safety check failure
  Makefile
  docs/changes.rst
Labels: review needed

#2978 Release 1.6.0
  .github/workflows/test.yml
  README_PYPI.rst
  docs/changes.rst
  pywbem/_version.py
Labels: rebase needed
