Repository pywbem/pywbem, pull requests merged in 2024-04, with the labels that each got.

#3137 Ks/#3136 indication callback queue
  pywbem/_listener.py
  tests/end2endtest/test_indications.py
  tests/unittest/pywbem/test_indicationlistener.py
Labels: review needed

#3158 Fix issue where listener startup failure can cause extra exceptions.
  docs/changes.rst
  pywbem/_listener.py
Labels: priority

#3160 1.7: Speed up install of dev. env. by pinning coverage
  dev-requirements.txt
  docs/changes.rst
Labels: area: devenv
